sprite $datomic [48x39/16z] {
rPJHbeGW28PJG07FZk__jaEQRZNQrDMUvPA-7twKN9R_5-0UuGwVyV2GHto4UvhntW_jJ7d0uRJp-kH6IO8f3oCx5poEx5pu-JHakHEF_LHmqDhiz2g-27t4
MQbgnxAhm56eEiy1d7E0kr9xEwi003csRrwOMfmCOSi7uTzI81As_76tNCULzvSFgd7xKj8a0drQYwXot1NiWdLYoZc_e4rBn6Uy23Yq1cfyZctQ84a-hvWq
rI6iWLI-be-QTBGH9gYUOC5NpZ--kkS9NWMbXP4SVN4Jn9Ap_GcgTMpVpYQkcVdlM0Jhs6XHYblGnRzQ1Dj11TPlU1EeC8lUm9iWMTp2UmUzYHy4znuggd3I
k-yQ6gkZdPc-i9AE-_xr2QU7R_AVnHi0
}
