
sprite $loginradius [48x48/16z] {
xTKn3aGX20HGHq6u_uaNNVF_LkjGs3cToGjHWsXsSpfI8r0dkRSo8WaF8EVBzMUyFw5yLrKHQP5Q-ywxbDym7cyuFme3VFtlLZ0wdFInKEu-LtsO9pnASxl-
-gHlAJ-wCkLHAkjNryS9A6-6oTZwCNNc8-nhFkozzzYGFlDdw-EzrecwZ2Z_LVwVd0Vo0G00
}
