sprite $snowflake [48x48/16z] {
pPLPSiGW34IjbVlVE0Oi146CpTIaCdofxCVIKYEEu-i7j00UqAWgXGDHfNjUaoRE0ITLlTq1JaWbH_9XlggB-4XtKGSH3sGPw4TH9pJpT2vqPM3YyuoHBtJ4
5yw6ypRcGj0hFgeRy8hdHLPH8bvm1X7w6Kay0qO3ud1q0ejJgiV55jKQD15mPT9ayBKIiXtyoYhq_71Ge4vZasMV-7SYG58o2tZQECWzcPVCCnJMm1UHYZFN
2RAg0TWVF2ZbhJcR1cqLYFpydDyyZuigdpkzdQbSxsO-T-i5mtudslpWffhgo_xB_UQBy51Vf7i_4wvls71VLhThypvktdTytK_mOR_YLR-gVDGFOxwOBEwt
7Fbvjv___Vlotdkt_PxkljV_F7u0
}
